# Lab | Pandas

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

The data includes information such as customer ID, state, gender, education, income, and other variables that can be used to perform various analyses.

Throughout the lab, we will be using the pandas library in Python to manipulate and analyze the data. Pandas is a powerful library that provides various data manipulation and analysis tools, including the ability to load and manipulate data from a variety of sources, including CSV files.

In [13]:
import pandas as pd

url = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv'

### Data Description

- Customer - Customer ID

- ST - State where customers live

- Gender - Gender of the customer

- Education - Background education of customers 

- Customer Lifetime Value - Customer lifetime value(CLV) is the total revenue the client will derive from their entire relationship with a customer. In other words, is the predicted or calculated value of a customer over their entire duration as a policyholder with the insurance company. It is an estimation of the net profit that the insurance company expects to generate from a customer throughout their relationship with the company. Customer Lifetime Value takes into account factors such as the duration of the customer's policy, premium payments, claim history, renewal likelihood, and potential additional services or products the customer may purchase. It helps insurers assess the long-term profitability and value associated with retaining a particular customer.

- Income - Customers income

- Monthly Premium Auto - Amount of money the customer pays on a monthly basis as a premium for their auto insurance coverage. It represents the recurring cost that the insured person must pay to maintain their insurance policy and receive coverage for potential damages, accidents, or other covered events related to their vehicle.

- Number of Open Complaints - Number of complaints the customer opened

- Policy Type - There are three type of policies in car insurance (Corporate Auto, Personal Auto, and Special Auto)

- Vehicle Class - Type of vehicle classes that customers have Two-Door Car, Four-Door Car SUV, Luxury SUV, Sports Car, and Luxury Car

- Total Claim Amount - the sum of all claims made by the customer. It represents the total monetary value of all approved claims for incidents such as accidents, theft, vandalism, or other covered events.

External Resources: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

## Challenge 1: Understanding the data

In this challenge, you will use pandas to explore a given dataset. Your task is to gain a deep understanding of the data by analyzing its characteristics, dimensions, and statistical properties.

- Identify the dimensions of the dataset by determining the number of rows and columns it contains.
- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.
- Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.
- Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
- Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [59]:
dataset = pd.read_csv(url)

# Identify the dimensions of the dataset by determining the number of rows and columns it contains.

print(dataset.shape)

# Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.

print(dataset.dtypes)

# Customer - String
# ST - String
# Gender - String
# Education - String
# Customer Lifetime Value - Float
# Income - Float
# Monthly Premium Auto - Float
# Number of Open Complaints - Integer
# Policy Type - String
# Vehicle Class - String
# Total Claim Amount - Float

# Customer Lifetime Value it's a string, but it should be a float. We can convert it to float by analyzing the data and removing any non-numeric characters, such as currency symbols or commas, before converting it to a float:

print(dataset["Customer Lifetime Value"].head())
print(dataset["Customer Lifetime Value"].dtype)

dataset["Customer Lifetime Value"] = dataset["Customer Lifetime Value"].str.replace("%", "")
dataset["Customer Lifetime Value"] = pd.to_numeric(dataset["Customer Lifetime Value"])

print(dataset["Customer Lifetime Value"].head())
print(dataset["Customer Lifetime Value"].dtype)

# Number of Open Complaint it's a string, but it should be a integer. We can convert it to integer by analyzing the data and removing any non-numeric characters, such as currency symbols or commas, before converting it to a integer:

print(dataset["Number of Open Complaints"].head())
print(dataset["Number of Open Complaints"].dtype)

dataset["Number of Open Complaints"] = dataset["Number of Open Complaints"].astype(str)
dataset["Number of Open Complaints"] =dataset["Number of Open Complaints"].str.split("/").str[1]
dataset["Number of Open Complaints"] = pd.to_numeric(dataset["Number of Open Complaints"])
dataset["Number of Open Complaints"] = dataset["Number of Open Complaints"].astype("Int64")

print(dataset["Number of Open Complaints"].head())
print(dataset["Number of Open Complaints"].dtype)

# Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.

print(dataset.nunique())

#GENDER                          5
#Education                       6
#Policy Type                     3
#Vehicle Class                   6

print(dataset["GENDER"].unique())
print(dataset["Education"].unique())
print(dataset["Policy Type"].unique())
print(dataset["Vehicle Class"].unique())

#Gender, Education, Policy Type and Vehicle Class are categorical. They should be:
#Gender: Female, Male
#Education: 'High School or Below', 'Bachelor', 'Master', 'Doctor'
#Policy Type: 'Personal Auto', 'Corporate Auto', 'Special Auto'
#Vehicle Class: 'Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury SUV', 'Sports Car', 'Luxury Car',         


# Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
# Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

dataset.describe()

(4008, 11)
Customer                         str
ST                               str
GENDER                           str
Education                        str
Customer Lifetime Value          str
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints        str
Policy Type                      str
Vehicle Class                    str
Total Claim Amount           float64
dtype: object
0            NaN
1     697953.59%
2    1288743.17%
3     764586.18%
4     536307.65%
Name: Customer Lifetime Value, dtype: str
str
0           NaN
1     697953.59
2    1288743.17
3     764586.18
4     536307.65
Name: Customer Lifetime Value, dtype: float64
float64
0    1/0/00
1    1/0/00
2    1/0/00
3    1/0/00
4    1/0/00
Name: Number of Open Complaints, dtype: str
str
0    0
1    0
2    0
3    0
4    0
Name: Number of Open Complaints, dtype: Int64
Int64
Customer                     1071
ST                              8
GENDER                          5
Education                       6
Customer Lifetime Value      1027
Income                        774
Monthly Premium Auto          132
Number of Open Complaints       6
Policy Type                     3
Vehicle Class                   6
Total Claim Amount            761
dtype: int64
<ArrowStringArray>
[nan, 'F', 'M', 'Femal', 'Male', 'female']
Length: 6, dtype: str
<ArrowStringArray>
[              'Master',             'Bachelor', 'High School or Below',
              'College',            'Bachelors',               'Doctor',
                    nan]
Length: 7, dtype: str
<ArrowStringArray>
['Personal Auto', 'Corporate Auto', 'Special Auto', nan]
Length: 4, dtype: str
<ArrowStringArray>
['Four-Door Car',  'Two-Door Car',           'SUV',    'Luxury SUV',
    'Sports Car',    'Luxury Car',             nan]
Length: 7, dtype: str

,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Total Claim Amount
count,1.068000e+03,1071.000000,1071.000000,1071.0,1071.000000
mean,7.936903e+05,39295.701214,193.234360,0.394024,404.986909
std,6.434784e+05,30469.427060,1601.190369,0.883769,293.027260
min,2.004351e+05,0.000000,61.000000,0.0,0.382107
25%,4.034080e+05,14072.000000,68.000000,0.0,202.157702
50%,5.881742e+05,36234.000000,83.000000,0.0,354.729129
75%,8.962872e+05,64631.000000,109.500000,0.0,532.800000
max,5.816655e+06,99960.000000,35354.000000,5.0,2893.239678

## Challenge 2: analyzing the data

### Exercise 1

The marketing team wants to know the top 5 less common customer locations. Create a pandas Series object that contains the customer locations and their frequencies, and then retrieve the top 5 less common locations in ascending order.

In [50]:
dataset = pd.read_csv(url)

dataset["ST"].value_counts().sort_values().head()

ST
AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Name: count, dtype: int64

### Exercise 2

The sales team wants to know the total number of policies sold for each type of policy. Create a pandas Series object that contains the policy types and their total number of policies sold, and then retrieve the policy type with the highest number of policies sold.

*Hint:*
- *Using value_counts() method simplifies this analysis.*
- *Futhermore, there is a method that returns the index of the maximum value in a column or row.*

In [55]:
dataset = pd.read_csv(url)

print(dataset["Policy Type"].value_counts())

print(dataset["Policy Type"].value_counts().idxmax())

Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64
Personal Auto

### Exercise 3

The sales team wants to know if customers with Personal Auto have a lower income than those with Corporate Auto. How does the average income compare between the two policy types?

- Use *loc* to create two dataframes: one containing only Personal Auto policies and one containing only Corporate Auto policies.
- Calculate the average income for each policy.
- Print the results.

In [56]:
personal_auto = dataset.loc[dataset["Policy Type"] == "Personal Auto"]
corporate_auto = dataset.loc[dataset["Policy Type"] == "Corporate Auto"]

personal_income = personal_auto["Income"].mean()
corporate_income = corporate_auto["Income"].mean()

print("Average income - Personal Auto:", personal_income)
print("Average income - Corporate Auto:", corporate_income)

Average income - Personal Auto: 38180.69871794872
Average income - Corporate Auto: 41390.31196581197

### Bonus: Exercise 4

Your goal is to identify customers with a high policy claim amount.

Instructions:

- Review again the statistics for total claim amount to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount data.

*Note: When analyzing data, we often want to focus on certain groups of values to gain insights. Percentiles are a useful tool to help us define these groups. A percentile is a measure that tells us what percentage of values in a dataset are below a certain value. For example, the 75th percentile represents the value below which 75% of the data falls. Similarly, the 25th percentile represents the value below which 25% of the data falls. When we talk about the top 25%, we are referring to the values that fall above the 75th percentile, which represent the top quarter of the data. On the other hand, when we talk about the bottom 25%, we are referring to the values that fall below the 25th percentile, which represent the bottom quarter of the data. By focusing on these groups, we can identify patterns and trends that may be useful for making decisions and taking action.*

*Hint: look for a method that gives you the percentile or quantile 0.75 and 0.25 for a Pandas Series.*

*Hint 2: check `Boolean selection according to the values of a single column` in https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*

In [60]:
dataset.describe()

,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Total Claim Amount
count,1.068000e+03,1071.000000,1071.000000,1071.0,1071.000000
mean,7.936903e+05,39295.701214,193.234360,0.394024,404.986909
std,6.434784e+05,30469.427060,1601.190369,0.883769,293.027260
min,2.004351e+05,0.000000,61.000000,0.0,0.382107
25%,4.034080e+05,14072.000000,68.000000,0.0,202.157702
50%,5.881742e+05,36234.000000,83.000000,0.0,354.729129
75%,8.962872e+05,64631.000000,109.500000,0.0,532.800000
max,5.816655e+06,99960.000000,35354.000000,5.0,2893.239678

In [64]:
high_claim = dataset.loc[dataset["Total Claim Amount"] > dataset["Total Claim Amount"].quantile(0.75)]

high_claim.describe()

,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Total Claim Amount
count,2.640000e+02,264.000000,264.000000,264.0,264.000000
mean,9.086868e+05,23677.344697,165.193182,0.416667,782.228263
std,6.387678e+05,27013.483721,623.930992,0.943593,292.751640
min,2.287597e+05,0.000000,63.000000,0.0,537.600000
25%,4.723958e+05,0.000000,99.000000,0.0,606.521741
50%,7.781768e+05,18807.000000,114.000000,0.0,679.597985
75%,1.054430e+06,42423.750000,133.250000,0.0,851.400000
max,3.844586e+06,99316.000000,10202.000000,5.0,2893.239678